Overwatch on BTRFS?
lutris/docs pull request #35
Opened 2020-10-15 13:51 UTC by KingAnde

The old documentation says Overwatch does not work on BTRFS, but I personally can't find any example of this. I'm on the F33 beta right now and Overwatch seems to be working perfectly fine on BTRFS. Is this issue deprecated, or is something else at play (encryption etc.) Has anyone else tried bare metal as well?

Related Issue #28 mentions something similar, but it's been stale for quite a while now, so I'm submitting this PR.

If anyone else on BTRFS, OpenSuse, or F33 have experience/issues, please share!

2021-01-02 14:04 UTC, Limero commented
Overwatch on Fedora 33 with btrfs works fine for me. What was the intial reason to add the exception for btrfs to the instructions? @tannisroot

2021-01-17 08:40 UTC, markkuit commented
Can confirm the game works flawlessly for me under btrfs.

2021-03-06 17:04 UTC, tannisroot requested changes
I am ok with removing BTRFS warning but I don't want to suggest it as a filesystem

2021-03-06 17:54 UTC, nickavem commented
then should we remove the FS recommendation altogether?

2021-03-07 05:20 UTC, tannisroot commented
I believe the NTFS warning is still true so that's not an option.

2021-03-07 07:28 UTC, markkuit commented
FWIW, I've been playing games through Lutris and Proton on btrfs and btrfs over NFS without any issue whatsoever. Could never get them to work properly on NTFS though.

2021-03-07 14:54 UTC, nickavem reviewed
See my latest commit

2021-03-07 20:08 UTC, merged