Update dependencies for Fedora
lutris/docs pull request #39
Opened 2020-12-07 20:56 UTC by Limero

* gnutls.i686 is needed for battle.net login to work
* pulseaudio-libs.i686 is needed for battle.net not to crash after login
* -devel packages shouldn't be needed
* x86_64 dependencies are not needed (especially things like gnutls that is a dependency of systemd)
* It might be possible to remove sqlite2 or replace it with sqlite (3), but I don't want to break anything.

2021-03-06 17:03 UTC, tannisroot requested changes
Can you rebase this against current docs? thanks

2021-03-06 17:26 UTC, Limero commented
Sure. Done!

2021-05-02 18:58 UTC, AsciiWolf commented
@Limero Would it be possible to rebase it again and add `freetype.i686` dependency (`freetype.x86_64` is already installed on Fedora Workstation) from https://github.com/lutris/docs/pull/61? Thanks!

2021-05-10 11:08 UTC, Limero commented
> @Limero Would it be possible to rebase it again and add `freetype.i686` dependency (`freetype.x86_64` is already installed on Fedora Workstation) from #61? Thanks!

I have added freetype.i686 to the list now :)

2021-06-16 14:09 UTC, merged